name: DST-Aware Keep-Alive for Render Service

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch:         # allows manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pytz requests

      - name: Run wakeup script
        env:
          RENDER_URL: ${{ secrets.RENDER_URL }}
        run: python .github/scripts/wakeup.py
