name: DST-Aware Keep-Alive for Render Service

on:
  schedule:
    - cron: '*/5 * * * 1-5'  # Every 5 minutes, Mon–Fri
  workflow_dispatch:         # Allows manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render app during business hours
        run: |
          # Get current hour in US Central time (automatically handles DST)
          HOUR=$(TZ=America/Chicago date +'%H')

          if { [ "$HOUR" -ge 6 ] && [ "$HOUR" -lt 9 ] ; } || { [ "$HOUR" -ge 15 ] && [ "$HOUR" -lt 18 ] ; }; then
            echo "Within business hours. Pinging server..."
            curl -fsS https://qr-checkin-tn8u.onrender.com || echo "Ping failed!"
          else
            echo "Outside business hours. No ping sent."
          fi
