name: Wake Up and Keep Alive Render Service

on:
  schedule:
    # This schedule runs the job every 10 minutes, but only during
    # the specific hours you need, Monday through Friday.
    # All times are in UTC for GitHub Actions.

    # Morning Shift: 11:00 UTC to 13:59 UTC (6 AM to 8:59 AM CDT)
    - cron: '*/10 11-13 * * 1-5'

    # Afternoon Shift: 20:00 UTC to 22:59 UTC (3 PM to 5:59 PM CDT)
    - cron: '*/10 20-22 * * 1-5'

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server to keep it alive
        run: curl -s https://qr-checkin-tn8u.onrender.com > /dev/null